Resources: 
  PrimaryDnsRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # cloudfront
      HostedZoneName: ${self:custom.domain}.
      Name: ${self:custom.domain}
      Type: 'A'